{
  "writer-config": {
    "specification": {
      "accounts": [
        {
          "operation": "shift",
          "spec": {
            "name": "name",
            "kafkaKey": "kafkaKey",
            "id": "ud.cfc.customerId",
            "applicationCustomerId": "ud.cfc.applicationCustomerId",
            "#customers": "ud.cfc.sourceCategory",
            "#cfc": "ud.usedBy[]"
          }
        }
      ]
    },
    "mapping": {
      "customers": "accounts",
      "users": "persons",
      "vehicles": "vehicles",
      "devices": "sensors"
    }
  }
}